### ISSUE TITLE
Wrong switch window position in multi-monitor configuration

### ISSUE THREAD

**Issue by aabrame** [p91paul/gnome-shell-extensions-coverflowalttab#9] opened 2012-10-12 17:10 UTC
There is one small issue with multi-monitor: the origin of the switch window is set to 0,0 but its not necessarly the origin of the main monitor. As results, I can see only half of the switch window.

**Comment by p91paul** [comment] 2012-10-13 10:35
Duplicate of #4. See that issue.

**Closed as completed by p91paul** 2012-10-13 10:35 UTC
Labels: duplicate
