### ISSUE TITLE
sometimes the screen is twinkling when using coverflowalttab

### ISSUE THREAD

**Issue by javafuns** [p91paul/gnome-shell-extensions-coverflowalttab#12] opened 2012-10-18 01:57 UTC
My OS is debian, gnome shell 3.4.2

**Comment by p91paul** [comment] 2012-11-24 10:36
This seems to be related to your graphics card. What card are you using? What driver?

**Comment by javafuns** [comment] 2012-11-25 07:58
The graphics card of T410 is :
00:02.0 VGA compatible controller: Intel Corporation Core Processor
Integrated Graphics Controller (rev 02)

The driver is Intel® Ironlake Mobile.

Thanks

2012/11/24 p91paul notifications@github.com

**Comment by p91paul** [comment] 2012-11-25 10:24
I hoped you were using free drivers on an ATI or Nvidia card :)
Do you see something similar also on other animations, e.g when opening Activities? I know that this extension is a bit heavyweight graphically.... 
I've not a lot of time at the moment, but I'm joining my code with another fork of this extension, that maybe has fixed (I saw he worked on animation code).
If you want, try the following: in the code tab, you can see a combobox saying branch: master; select branch dm60-gnome-shell, then download zip, and put the folder CoverflowAltTab@dm60.de under .local/share/gnome-shell/extensions. Restart the shell, then disable a Coverflow and enable the other (they will have the same name :) ). Try if you continue to see the problem. My next release will be based on that work!

**Comment by javafuns** [comment] 2012-11-25 15:00
OK. I'll give it a try.

Thanks for your work

2012/11/25 p91paul notifications@github.com

**Comment by javafuns** [comment] 2012-11-26 02:03
Still not work fine.
After it's being used for a while, it is crashed, then all my window
environment disappears and soon comes back again.

Thanks

2012/11/25 Gavin Zhang guangquanzhang@gmail.com

**Comment by p91paul** [comment] 2012-12-17 23:49
This project, is closing, and development is going on here: https://github.com/dmo60/CoverflowAltTab/
If you continue to suffer this bug (a new version has been uploaded to extensions.gnome.org) please report there. I'm not copying this bug in the new repo since I cannot reproduce.

**Closed as completed by p91paul** 2012-12-17 23:49 UTC
